export {default as Header} from './Header/Header'
export {default as Kero} from './Kero/Kero'
export {default as MostPopular} from './MostPopular/MostPopular'
export {default as GamingLibrary} from './GamingLibrary/GamingLibrary'
export {default as Featured_Games} from './Featured_Games/Featured_Games'
export {default as Footer} from './Footer/Footer'
